// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessage.proto
package com.distributedsnapchat.communication.protobuf;
public final class ClientMessageProto {
  private ClientMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string message = 1;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>optional string clientSenderId = 2;</code>
     */
    boolean hasClientSenderId();
    /**
     * <code>optional string clientSenderId = 2;</code>
     */
    java.lang.String getClientSenderId();
    /**
     * <code>optional string clientSenderId = 2;</code>
     */
    com.google.protobuf.ByteString
        getClientSenderIdBytes();

    /**
     * <code>optional string clientSenderIp = 3;</code>
     */
    boolean hasClientSenderIp();
    /**
     * <code>optional string clientSenderIp = 3;</code>
     */
    java.lang.String getClientSenderIp();
    /**
     * <code>optional string clientSenderIp = 3;</code>
     */
    com.google.protobuf.ByteString
        getClientSenderIpBytes();

    /**
     * <code>optional int32 clientSenderPort = 4;</code>
     */
    boolean hasClientSenderPort();
    /**
     * <code>optional int32 clientSenderPort = 4;</code>
     */
    int getClientSenderPort();

    /**
     * <code>optional string clientReceiverId = 5;</code>
     */
    boolean hasClientReceiverId();
    /**
     * <code>optional string clientReceiverId = 5;</code>
     */
    java.lang.String getClientReceiverId();
    /**
     * <code>optional string clientReceiverId = 5;</code>
     */
    com.google.protobuf.ByteString
        getClientReceiverIdBytes();

    /**
     * <code>optional string clientReceiverIp = 6;</code>
     */
    boolean hasClientReceiverIp();
    /**
     * <code>optional string clientReceiverIp = 6;</code>
     */
    java.lang.String getClientReceiverIp();
    /**
     * <code>optional string clientReceiverIp = 6;</code>
     */
    com.google.protobuf.ByteString
        getClientReceiverIpBytes();

    /**
     * <code>optional int32 clientReceiverPort = 7;</code>
     */
    boolean hasClientReceiverPort();
    /**
     * <code>optional int32 clientReceiverPort = 7;</code>
     */
    int getClientReceiverPort();

    /**
     * <code>optional string fileName = 8;</code>
     */
    boolean hasFileName();
    /**
     * <code>optional string fileName = 8;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>optional string fileName = 8;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>optional bytes imageBits = 9;</code>
     */
    boolean hasImageBits();
    /**
     * <code>optional bytes imageBits = 9;</code>
     */
    com.google.protobuf.ByteString getImageBits();
  }
  /**
   * Protobuf type {@code ClientMessage}
   */
  public static final class ClientMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ClientMessage)
      ClientMessageOrBuilder {
    // Use ClientMessage.newBuilder() to construct.
    private ClientMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientMessage defaultInstance;
    public static ClientMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ClientMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              message_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              clientSenderId_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              clientSenderIp_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              clientSenderPort_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              clientReceiverId_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              clientReceiverIp_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              clientReceiverPort_ = input.readInt32();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              fileName_ = bs;
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              imageBits_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientMessageProto.internal_static_ClientMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientMessageProto.internal_static_ClientMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientMessageProto.ClientMessage.class, ClientMessageProto.ClientMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientMessage> PARSER =
        new com.google.protobuf.AbstractParser<ClientMessage>() {
      public ClientMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 1;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTSENDERID_FIELD_NUMBER = 2;
    private java.lang.Object clientSenderId_;
    /**
     * <code>optional string clientSenderId = 2;</code>
     */
    public boolean hasClientSenderId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string clientSenderId = 2;</code>
     */
    public java.lang.String getClientSenderId() {
      java.lang.Object ref = clientSenderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientSenderId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clientSenderId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientSenderIdBytes() {
      java.lang.Object ref = clientSenderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientSenderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTSENDERIP_FIELD_NUMBER = 3;
    private java.lang.Object clientSenderIp_;
    /**
     * <code>optional string clientSenderIp = 3;</code>
     */
    public boolean hasClientSenderIp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string clientSenderIp = 3;</code>
     */
    public java.lang.String getClientSenderIp() {
      java.lang.Object ref = clientSenderIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientSenderIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clientSenderIp = 3;</code>
     */
    public com.google.protobuf.ByteString
        getClientSenderIpBytes() {
      java.lang.Object ref = clientSenderIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientSenderIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTSENDERPORT_FIELD_NUMBER = 4;
    private int clientSenderPort_;
    /**
     * <code>optional int32 clientSenderPort = 4;</code>
     */
    public boolean hasClientSenderPort() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 clientSenderPort = 4;</code>
     */
    public int getClientSenderPort() {
      return clientSenderPort_;
    }

    public static final int CLIENTRECEIVERID_FIELD_NUMBER = 5;
    private java.lang.Object clientReceiverId_;
    /**
     * <code>optional string clientReceiverId = 5;</code>
     */
    public boolean hasClientReceiverId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string clientReceiverId = 5;</code>
     */
    public java.lang.String getClientReceiverId() {
      java.lang.Object ref = clientReceiverId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientReceiverId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clientReceiverId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getClientReceiverIdBytes() {
      java.lang.Object ref = clientReceiverId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientReceiverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTRECEIVERIP_FIELD_NUMBER = 6;
    private java.lang.Object clientReceiverIp_;
    /**
     * <code>optional string clientReceiverIp = 6;</code>
     */
    public boolean hasClientReceiverIp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string clientReceiverIp = 6;</code>
     */
    public java.lang.String getClientReceiverIp() {
      java.lang.Object ref = clientReceiverIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientReceiverIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clientReceiverIp = 6;</code>
     */
    public com.google.protobuf.ByteString
        getClientReceiverIpBytes() {
      java.lang.Object ref = clientReceiverIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientReceiverIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTRECEIVERPORT_FIELD_NUMBER = 7;
    private int clientReceiverPort_;
    /**
     * <code>optional int32 clientReceiverPort = 7;</code>
     */
    public boolean hasClientReceiverPort() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 clientReceiverPort = 7;</code>
     */
    public int getClientReceiverPort() {
      return clientReceiverPort_;
    }

    public static final int FILENAME_FIELD_NUMBER = 8;
    private java.lang.Object fileName_;
    /**
     * <code>optional string fileName = 8;</code>
     */
    public boolean hasFileName() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string fileName = 8;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string fileName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGEBITS_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString imageBits_;
    /**
     * <code>optional bytes imageBits = 9;</code>
     */
    public boolean hasImageBits() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional bytes imageBits = 9;</code>
     */
    public com.google.protobuf.ByteString getImageBits() {
      return imageBits_;
    }

    private void initFields() {
      message_ = "";
      clientSenderId_ = "";
      clientSenderIp_ = "";
      clientSenderPort_ = 0;
      clientReceiverId_ = "";
      clientReceiverIp_ = "";
      clientReceiverPort_ = 0;
      fileName_ = "";
      imageBits_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getClientSenderIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getClientSenderIpBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, clientSenderPort_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getClientReceiverIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getClientReceiverIpBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, clientReceiverPort_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, imageBits_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getClientSenderIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getClientSenderIpBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, clientSenderPort_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getClientReceiverIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getClientReceiverIpBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, clientReceiverPort_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, imageBits_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ClientMessageProto.ClientMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientMessageProto.ClientMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientMessageProto.ClientMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientMessageProto.ClientMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientMessageProto.ClientMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientMessageProto.ClientMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ClientMessageProto.ClientMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ClientMessageProto.ClientMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ClientMessageProto.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientMessageProto.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ClientMessageProto.ClientMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientMessage)
        ClientMessageProto.ClientMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientMessageProto.internal_static_ClientMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientMessageProto.internal_static_ClientMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientMessageProto.ClientMessage.class, ClientMessageProto.ClientMessage.Builder.class);
      }

      // Construct using ClientMessageProto.ClientMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        clientSenderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        clientSenderIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        clientSenderPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        clientReceiverId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        clientReceiverIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        clientReceiverPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        fileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        imageBits_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClientMessageProto.internal_static_ClientMessage_descriptor;
      }

      public ClientMessageProto.ClientMessage getDefaultInstanceForType() {
        return ClientMessageProto.ClientMessage.getDefaultInstance();
      }

      public ClientMessageProto.ClientMessage build() {
        ClientMessageProto.ClientMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ClientMessageProto.ClientMessage buildPartial() {
        ClientMessageProto.ClientMessage result = new ClientMessageProto.ClientMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientSenderId_ = clientSenderId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.clientSenderIp_ = clientSenderIp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.clientSenderPort_ = clientSenderPort_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.clientReceiverId_ = clientReceiverId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.clientReceiverIp_ = clientReceiverIp_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.clientReceiverPort_ = clientReceiverPort_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.fileName_ = fileName_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.imageBits_ = imageBits_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientMessageProto.ClientMessage) {
          return mergeFrom((ClientMessageProto.ClientMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientMessageProto.ClientMessage other) {
        if (other == ClientMessageProto.ClientMessage.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          bitField0_ |= 0x00000001;
          message_ = other.message_;
          onChanged();
        }
        if (other.hasClientSenderId()) {
          bitField0_ |= 0x00000002;
          clientSenderId_ = other.clientSenderId_;
          onChanged();
        }
        if (other.hasClientSenderIp()) {
          bitField0_ |= 0x00000004;
          clientSenderIp_ = other.clientSenderIp_;
          onChanged();
        }
        if (other.hasClientSenderPort()) {
          setClientSenderPort(other.getClientSenderPort());
        }
        if (other.hasClientReceiverId()) {
          bitField0_ |= 0x00000010;
          clientReceiverId_ = other.clientReceiverId_;
          onChanged();
        }
        if (other.hasClientReceiverIp()) {
          bitField0_ |= 0x00000020;
          clientReceiverIp_ = other.clientReceiverIp_;
          onChanged();
        }
        if (other.hasClientReceiverPort()) {
          setClientReceiverPort(other.getClientReceiverPort());
        }
        if (other.hasFileName()) {
          bitField0_ |= 0x00000080;
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.hasImageBits()) {
          setImageBits(other.getImageBits());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClientMessageProto.ClientMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ClientMessageProto.ClientMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 1;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientSenderId_ = "";
      /**
       * <code>optional string clientSenderId = 2;</code>
       */
      public boolean hasClientSenderId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string clientSenderId = 2;</code>
       */
      public java.lang.String getClientSenderId() {
        java.lang.Object ref = clientSenderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientSenderId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientSenderId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClientSenderIdBytes() {
        java.lang.Object ref = clientSenderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientSenderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientSenderId = 2;</code>
       */
      public Builder setClientSenderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientSenderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientSenderId = 2;</code>
       */
      public Builder clearClientSenderId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientSenderId_ = getDefaultInstance().getClientSenderId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientSenderId = 2;</code>
       */
      public Builder setClientSenderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientSenderId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientSenderIp_ = "";
      /**
       * <code>optional string clientSenderIp = 3;</code>
       */
      public boolean hasClientSenderIp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string clientSenderIp = 3;</code>
       */
      public java.lang.String getClientSenderIp() {
        java.lang.Object ref = clientSenderIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientSenderIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientSenderIp = 3;</code>
       */
      public com.google.protobuf.ByteString
          getClientSenderIpBytes() {
        java.lang.Object ref = clientSenderIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientSenderIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientSenderIp = 3;</code>
       */
      public Builder setClientSenderIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        clientSenderIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientSenderIp = 3;</code>
       */
      public Builder clearClientSenderIp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clientSenderIp_ = getDefaultInstance().getClientSenderIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientSenderIp = 3;</code>
       */
      public Builder setClientSenderIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        clientSenderIp_ = value;
        onChanged();
        return this;
      }

      private int clientSenderPort_ ;
      /**
       * <code>optional int32 clientSenderPort = 4;</code>
       */
      public boolean hasClientSenderPort() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 clientSenderPort = 4;</code>
       */
      public int getClientSenderPort() {
        return clientSenderPort_;
      }
      /**
       * <code>optional int32 clientSenderPort = 4;</code>
       */
      public Builder setClientSenderPort(int value) {
        bitField0_ |= 0x00000008;
        clientSenderPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clientSenderPort = 4;</code>
       */
      public Builder clearClientSenderPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        clientSenderPort_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object clientReceiverId_ = "";
      /**
       * <code>optional string clientReceiverId = 5;</code>
       */
      public boolean hasClientReceiverId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string clientReceiverId = 5;</code>
       */
      public java.lang.String getClientReceiverId() {
        java.lang.Object ref = clientReceiverId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientReceiverId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientReceiverId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getClientReceiverIdBytes() {
        java.lang.Object ref = clientReceiverId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientReceiverId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientReceiverId = 5;</code>
       */
      public Builder setClientReceiverId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        clientReceiverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientReceiverId = 5;</code>
       */
      public Builder clearClientReceiverId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        clientReceiverId_ = getDefaultInstance().getClientReceiverId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientReceiverId = 5;</code>
       */
      public Builder setClientReceiverIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        clientReceiverId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientReceiverIp_ = "";
      /**
       * <code>optional string clientReceiverIp = 6;</code>
       */
      public boolean hasClientReceiverIp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string clientReceiverIp = 6;</code>
       */
      public java.lang.String getClientReceiverIp() {
        java.lang.Object ref = clientReceiverIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientReceiverIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientReceiverIp = 6;</code>
       */
      public com.google.protobuf.ByteString
          getClientReceiverIpBytes() {
        java.lang.Object ref = clientReceiverIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientReceiverIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientReceiverIp = 6;</code>
       */
      public Builder setClientReceiverIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        clientReceiverIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientReceiverIp = 6;</code>
       */
      public Builder clearClientReceiverIp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        clientReceiverIp_ = getDefaultInstance().getClientReceiverIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientReceiverIp = 6;</code>
       */
      public Builder setClientReceiverIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        clientReceiverIp_ = value;
        onChanged();
        return this;
      }

      private int clientReceiverPort_ ;
      /**
       * <code>optional int32 clientReceiverPort = 7;</code>
       */
      public boolean hasClientReceiverPort() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 clientReceiverPort = 7;</code>
       */
      public int getClientReceiverPort() {
        return clientReceiverPort_;
      }
      /**
       * <code>optional int32 clientReceiverPort = 7;</code>
       */
      public Builder setClientReceiverPort(int value) {
        bitField0_ |= 0x00000040;
        clientReceiverPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clientReceiverPort = 7;</code>
       */
      public Builder clearClientReceiverPort() {
        bitField0_ = (bitField0_ & ~0x00000040);
        clientReceiverPort_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>optional string fileName = 8;</code>
       */
      public boolean hasFileName() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string fileName = 8;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fileName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string fileName = 8;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string fileName = 8;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string fileName = 8;</code>
       */
      public Builder clearFileName() {
        bitField0_ = (bitField0_ & ~0x00000080);
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string fileName = 8;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        fileName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString imageBits_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes imageBits = 9;</code>
       */
      public boolean hasImageBits() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional bytes imageBits = 9;</code>
       */
      public com.google.protobuf.ByteString getImageBits() {
        return imageBits_;
      }
      /**
       * <code>optional bytes imageBits = 9;</code>
       */
      public Builder setImageBits(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        imageBits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes imageBits = 9;</code>
       */
      public Builder clearImageBits() {
        bitField0_ = (bitField0_ & ~0x00000100);
        imageBits_ = getDefaultInstance().getImageBits();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ClientMessage)
    }

    static {
      defaultInstance = new ClientMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ClientMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClientMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClientMessage.proto\"\337\001\n\rClientMessage\022" +
      "\017\n\007message\030\001 \001(\t\022\026\n\016clientSenderId\030\002 \001(\t" +
      "\022\026\n\016clientSenderIp\030\003 \001(\t\022\030\n\020clientSender" +
      "Port\030\004 \001(\005\022\030\n\020clientReceiverId\030\005 \001(\t\022\030\n\020" +
      "clientReceiverIp\030\006 \001(\t\022\032\n\022clientReceiver" +
      "Port\030\007 \001(\005\022\020\n\010fileName\030\010 \001(\t\022\021\n\timageBit" +
      "s\030\t \001(\014B\024B\022ClientMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ClientMessage_descriptor,
        new java.lang.String[] { "Message", "ClientSenderId", "ClientSenderIp", "ClientSenderPort", "ClientReceiverId", "ClientReceiverIp", "ClientReceiverPort", "FileName", "ImageBits", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
