// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NodeMessage.proto
package com.distributedsnapchat.communication.protobuf;

public final class NodeMessageProto {
  private NodeMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string message = 1;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>optional string nodeId = 2;</code>
     */
    boolean hasNodeId();
    /**
     * <code>optional string nodeId = 2;</code>
     */
    java.lang.String getNodeId();
    /**
     * <code>optional string nodeId = 2;</code>
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();

    /**
     * <code>optional string nodeIp = 3;</code>
     */
    boolean hasNodeIp();
    /**
     * <code>optional string nodeIp = 3;</code>
     */
    java.lang.String getNodeIp();
    /**
     * <code>optional string nodeIp = 3;</code>
     */
    com.google.protobuf.ByteString
        getNodeIpBytes();

    /**
     * <code>optional int32 nodePort = 4;</code>
     */
    boolean hasNodePort();
    /**
     * <code>optional int32 nodePort = 4;</code>
     */
    int getNodePort();

    /**
     * <code>optional .ClientMessage clientMessage = 5;</code>
     */
    boolean hasClientMessage();
    /**
     * <code>optional .ClientMessage clientMessage = 5;</code>
     */
    NodeMessageProto.ClientMessage getClientMessage();
    /**
     * <code>optional .ClientMessage clientMessage = 5;</code>
     */
    NodeMessageProto.ClientMessageOrBuilder getClientMessageOrBuilder();

    /**
     * <code>optional .Message.MessageType messageType = 6 [default = HEARTBEAT];</code>
     */
    boolean hasMessageType();
    /**
     * <code>optional .Message.MessageType messageType = 6 [default = HEARTBEAT];</code>
     */
    NodeMessageProto.Message.MessageType getMessageType();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              message_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              nodeId_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              nodeIp_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              nodePort_ = input.readInt32();
              break;
            }
            case 42: {
              NodeMessageProto.ClientMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = clientMessage_.toBuilder();
              }
              clientMessage_ = input.readMessage(NodeMessageProto.ClientMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(clientMessage_);
                clientMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              NodeMessageProto.Message.MessageType value = NodeMessageProto.Message.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                messageType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NodeMessageProto.internal_static_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NodeMessageProto.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NodeMessageProto.Message.class, NodeMessageProto.Message.Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Message.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HEARTBEAT = 0;</code>
       */
      HEARTBEAT(0, 0),
      /**
       * <code>NOMINATION = 1;</code>
       */
      NOMINATION(1, 1),
      /**
       * <code>VOTE = 2;</code>
       */
      VOTE(2, 2),
      /**
       * <code>LOG_REPLICATION_REQUEST = 3;</code>
       */
      LOG_REPLICATION_REQUEST(3, 3),
      /**
       * <code>LOG_REPLICATION_COMPLETE_NOTIFICATION = 4;</code>
       */
      LOG_REPLICATION_COMPLETE_NOTIFICATION(4, 4),
      ;

      /**
       * <code>HEARTBEAT = 0;</code>
       */
      public static final int HEARTBEAT_VALUE = 0;
      /**
       * <code>NOMINATION = 1;</code>
       */
      public static final int NOMINATION_VALUE = 1;
      /**
       * <code>VOTE = 2;</code>
       */
      public static final int VOTE_VALUE = 2;
      /**
       * <code>LOG_REPLICATION_REQUEST = 3;</code>
       */
      public static final int LOG_REPLICATION_REQUEST_VALUE = 3;
      /**
       * <code>LOG_REPLICATION_COMPLETE_NOTIFICATION = 4;</code>
       */
      public static final int LOG_REPLICATION_COMPLETE_NOTIFICATION_VALUE = 4;


      public final int getNumber() { return value; }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 0: return HEARTBEAT;
          case 1: return NOMINATION;
          case 2: return VOTE;
          case 3: return LOG_REPLICATION_REQUEST;
          case 4: return LOG_REPLICATION_COMPLETE_NOTIFICATION;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return NodeMessageProto.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Message.MessageType)
    }

    private int bitField0_;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 1;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODEID_FIELD_NUMBER = 2;
    private java.lang.Object nodeId_;
    /**
     * <code>optional string nodeId = 2;</code>
     */
    public boolean hasNodeId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string nodeId = 2;</code>
     */
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nodeId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nodeId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODEIP_FIELD_NUMBER = 3;
    private java.lang.Object nodeIp_;
    /**
     * <code>optional string nodeIp = 3;</code>
     */
    public boolean hasNodeIp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string nodeIp = 3;</code>
     */
    public java.lang.String getNodeIp() {
      java.lang.Object ref = nodeIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nodeIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nodeIp = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNodeIpBytes() {
      java.lang.Object ref = nodeIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODEPORT_FIELD_NUMBER = 4;
    private int nodePort_;
    /**
     * <code>optional int32 nodePort = 4;</code>
     */
    public boolean hasNodePort() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 nodePort = 4;</code>
     */
    public int getNodePort() {
      return nodePort_;
    }

    public static final int CLIENTMESSAGE_FIELD_NUMBER = 5;
    private NodeMessageProto.ClientMessage clientMessage_;
    /**
     * <code>optional .ClientMessage clientMessage = 5;</code>
     */
    public boolean hasClientMessage() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .ClientMessage clientMessage = 5;</code>
     */
    public NodeMessageProto.ClientMessage getClientMessage() {
      return clientMessage_;
    }
    /**
     * <code>optional .ClientMessage clientMessage = 5;</code>
     */
    public NodeMessageProto.ClientMessageOrBuilder getClientMessageOrBuilder() {
      return clientMessage_;
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 6;
    private NodeMessageProto.Message.MessageType messageType_;
    /**
     * <code>optional .Message.MessageType messageType = 6 [default = HEARTBEAT];</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .Message.MessageType messageType = 6 [default = HEARTBEAT];</code>
     */
    public NodeMessageProto.Message.MessageType getMessageType() {
      return messageType_;
    }

    private void initFields() {
      message_ = "";
      nodeId_ = "";
      nodeIp_ = "";
      nodePort_ = 0;
      clientMessage_ = NodeMessageProto.ClientMessage.getDefaultInstance();
      messageType_ = NodeMessageProto.Message.MessageType.HEARTBEAT;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNodeIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNodeIpBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, nodePort_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, clientMessage_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, messageType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNodeIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNodeIpBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, nodePort_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, clientMessage_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, messageType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static NodeMessageProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NodeMessageProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NodeMessageProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NodeMessageProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NodeMessageProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NodeMessageProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static NodeMessageProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static NodeMessageProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static NodeMessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NodeMessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(NodeMessageProto.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        NodeMessageProto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NodeMessageProto.internal_static_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NodeMessageProto.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NodeMessageProto.Message.class, NodeMessageProto.Message.Builder.class);
      }

      // Construct using NodeMessageProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getClientMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        nodeIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        nodePort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (clientMessageBuilder_ == null) {
          clientMessage_ = NodeMessageProto.ClientMessage.getDefaultInstance();
        } else {
          clientMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        messageType_ = NodeMessageProto.Message.MessageType.HEARTBEAT;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NodeMessageProto.internal_static_Message_descriptor;
      }

      public NodeMessageProto.Message getDefaultInstanceForType() {
        return NodeMessageProto.Message.getDefaultInstance();
      }

      public NodeMessageProto.Message build() {
        NodeMessageProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NodeMessageProto.Message buildPartial() {
        NodeMessageProto.Message result = new NodeMessageProto.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nodeId_ = nodeId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.nodeIp_ = nodeIp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.nodePort_ = nodePort_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (clientMessageBuilder_ == null) {
          result.clientMessage_ = clientMessage_;
        } else {
          result.clientMessage_ = clientMessageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.messageType_ = messageType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NodeMessageProto.Message) {
          return mergeFrom((NodeMessageProto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NodeMessageProto.Message other) {
        if (other == NodeMessageProto.Message.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          bitField0_ |= 0x00000001;
          message_ = other.message_;
          onChanged();
        }
        if (other.hasNodeId()) {
          bitField0_ |= 0x00000002;
          nodeId_ = other.nodeId_;
          onChanged();
        }
        if (other.hasNodeIp()) {
          bitField0_ |= 0x00000004;
          nodeIp_ = other.nodeIp_;
          onChanged();
        }
        if (other.hasNodePort()) {
          setNodePort(other.getNodePort());
        }
        if (other.hasClientMessage()) {
          mergeClientMessage(other.getClientMessage());
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NodeMessageProto.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NodeMessageProto.Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 1;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nodeId_ = "";
      /**
       * <code>optional string nodeId = 2;</code>
       */
      public boolean hasNodeId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string nodeId = 2;</code>
       */
      public java.lang.String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nodeId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nodeId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        java.lang.Object ref = nodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nodeId = 2;</code>
       */
      public Builder setNodeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nodeId = 2;</code>
       */
      public Builder clearNodeId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nodeId_ = getDefaultInstance().getNodeId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nodeId = 2;</code>
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nodeId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nodeIp_ = "";
      /**
       * <code>optional string nodeIp = 3;</code>
       */
      public boolean hasNodeIp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string nodeIp = 3;</code>
       */
      public java.lang.String getNodeIp() {
        java.lang.Object ref = nodeIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nodeIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nodeIp = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNodeIpBytes() {
        java.lang.Object ref = nodeIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nodeIp = 3;</code>
       */
      public Builder setNodeIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nodeIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nodeIp = 3;</code>
       */
      public Builder clearNodeIp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        nodeIp_ = getDefaultInstance().getNodeIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nodeIp = 3;</code>
       */
      public Builder setNodeIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nodeIp_ = value;
        onChanged();
        return this;
      }

      private int nodePort_ ;
      /**
       * <code>optional int32 nodePort = 4;</code>
       */
      public boolean hasNodePort() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 nodePort = 4;</code>
       */
      public int getNodePort() {
        return nodePort_;
      }
      /**
       * <code>optional int32 nodePort = 4;</code>
       */
      public Builder setNodePort(int value) {
        bitField0_ |= 0x00000008;
        nodePort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 nodePort = 4;</code>
       */
      public Builder clearNodePort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        nodePort_ = 0;
        onChanged();
        return this;
      }

      private NodeMessageProto.ClientMessage clientMessage_ = NodeMessageProto.ClientMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          NodeMessageProto.ClientMessage, NodeMessageProto.ClientMessage.Builder, NodeMessageProto.ClientMessageOrBuilder> clientMessageBuilder_;
      /**
       * <code>optional .ClientMessage clientMessage = 5;</code>
       */
      public boolean hasClientMessage() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .ClientMessage clientMessage = 5;</code>
       */
      public NodeMessageProto.ClientMessage getClientMessage() {
        if (clientMessageBuilder_ == null) {
          return clientMessage_;
        } else {
          return clientMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ClientMessage clientMessage = 5;</code>
       */
      public Builder setClientMessage(NodeMessageProto.ClientMessage value) {
        if (clientMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          clientMessage_ = value;
          onChanged();
        } else {
          clientMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .ClientMessage clientMessage = 5;</code>
       */
      public Builder setClientMessage(
          NodeMessageProto.ClientMessage.Builder builderForValue) {
        if (clientMessageBuilder_ == null) {
          clientMessage_ = builderForValue.build();
          onChanged();
        } else {
          clientMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .ClientMessage clientMessage = 5;</code>
       */
      public Builder mergeClientMessage(NodeMessageProto.ClientMessage value) {
        if (clientMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              clientMessage_ != NodeMessageProto.ClientMessage.getDefaultInstance()) {
            clientMessage_ =
              NodeMessageProto.ClientMessage.newBuilder(clientMessage_).mergeFrom(value).buildPartial();
          } else {
            clientMessage_ = value;
          }
          onChanged();
        } else {
          clientMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .ClientMessage clientMessage = 5;</code>
       */
      public Builder clearClientMessage() {
        if (clientMessageBuilder_ == null) {
          clientMessage_ = NodeMessageProto.ClientMessage.getDefaultInstance();
          onChanged();
        } else {
          clientMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .ClientMessage clientMessage = 5;</code>
       */
      public NodeMessageProto.ClientMessage.Builder getClientMessageBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getClientMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ClientMessage clientMessage = 5;</code>
       */
      public NodeMessageProto.ClientMessageOrBuilder getClientMessageOrBuilder() {
        if (clientMessageBuilder_ != null) {
          return clientMessageBuilder_.getMessageOrBuilder();
        } else {
          return clientMessage_;
        }
      }
      /**
       * <code>optional .ClientMessage clientMessage = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          NodeMessageProto.ClientMessage, NodeMessageProto.ClientMessage.Builder, NodeMessageProto.ClientMessageOrBuilder> 
          getClientMessageFieldBuilder() {
        if (clientMessageBuilder_ == null) {
          clientMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              NodeMessageProto.ClientMessage, NodeMessageProto.ClientMessage.Builder, NodeMessageProto.ClientMessageOrBuilder>(
                  getClientMessage(),
                  getParentForChildren(),
                  isClean());
          clientMessage_ = null;
        }
        return clientMessageBuilder_;
      }

      private NodeMessageProto.Message.MessageType messageType_ = NodeMessageProto.Message.MessageType.HEARTBEAT;
      /**
       * <code>optional .Message.MessageType messageType = 6 [default = HEARTBEAT];</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .Message.MessageType messageType = 6 [default = HEARTBEAT];</code>
       */
      public NodeMessageProto.Message.MessageType getMessageType() {
        return messageType_;
      }
      /**
       * <code>optional .Message.MessageType messageType = 6 [default = HEARTBEAT];</code>
       */
      public Builder setMessageType(NodeMessageProto.Message.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Message.MessageType messageType = 6 [default = HEARTBEAT];</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        messageType_ = NodeMessageProto.Message.MessageType.HEARTBEAT;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Message)
  }

  public interface ClientMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string message = 1;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>optional string clientSenderId = 2;</code>
     */
    boolean hasClientSenderId();
    /**
     * <code>optional string clientSenderId = 2;</code>
     */
    java.lang.String getClientSenderId();
    /**
     * <code>optional string clientSenderId = 2;</code>
     */
    com.google.protobuf.ByteString
        getClientSenderIdBytes();

    /**
     * <code>optional string clientSenderIp = 3;</code>
     */
    boolean hasClientSenderIp();
    /**
     * <code>optional string clientSenderIp = 3;</code>
     */
    java.lang.String getClientSenderIp();
    /**
     * <code>optional string clientSenderIp = 3;</code>
     */
    com.google.protobuf.ByteString
        getClientSenderIpBytes();

    /**
     * <code>optional int32 clientSenderPort = 4;</code>
     */
    boolean hasClientSenderPort();
    /**
     * <code>optional int32 clientSenderPort = 4;</code>
     */
    int getClientSenderPort();

    /**
     * <code>optional string clientReceiverId = 5;</code>
     */
    boolean hasClientReceiverId();
    /**
     * <code>optional string clientReceiverId = 5;</code>
     */
    java.lang.String getClientReceiverId();
    /**
     * <code>optional string clientReceiverId = 5;</code>
     */
    com.google.protobuf.ByteString
        getClientReceiverIdBytes();

    /**
     * <code>optional string clientReceiverIp = 6;</code>
     */
    boolean hasClientReceiverIp();
    /**
     * <code>optional string clientReceiverIp = 6;</code>
     */
    java.lang.String getClientReceiverIp();
    /**
     * <code>optional string clientReceiverIp = 6;</code>
     */
    com.google.protobuf.ByteString
        getClientReceiverIpBytes();

    /**
     * <code>optional int32 clientReceiverPort = 7;</code>
     */
    boolean hasClientReceiverPort();
    /**
     * <code>optional int32 clientReceiverPort = 7;</code>
     */
    int getClientReceiverPort();

    /**
     * <code>optional string fileName = 8;</code>
     */
    boolean hasFileName();
    /**
     * <code>optional string fileName = 8;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>optional string fileName = 8;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>optional bytes imageBits = 9;</code>
     */
    boolean hasImageBits();
    /**
     * <code>optional bytes imageBits = 9;</code>
     */
    com.google.protobuf.ByteString getImageBits();
  }
  /**
   * Protobuf type {@code ClientMessage}
   */
  public static final class ClientMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ClientMessage)
      ClientMessageOrBuilder {
    // Use ClientMessage.newBuilder() to construct.
    private ClientMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientMessage defaultInstance;
    public static ClientMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ClientMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              message_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              clientSenderId_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              clientSenderIp_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              clientSenderPort_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              clientReceiverId_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              clientReceiverIp_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              clientReceiverPort_ = input.readInt32();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              fileName_ = bs;
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              imageBits_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NodeMessageProto.internal_static_ClientMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NodeMessageProto.internal_static_ClientMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NodeMessageProto.ClientMessage.class, NodeMessageProto.ClientMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientMessage> PARSER =
        new com.google.protobuf.AbstractParser<ClientMessage>() {
      public ClientMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 1;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTSENDERID_FIELD_NUMBER = 2;
    private java.lang.Object clientSenderId_;
    /**
     * <code>optional string clientSenderId = 2;</code>
     */
    public boolean hasClientSenderId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string clientSenderId = 2;</code>
     */
    public java.lang.String getClientSenderId() {
      java.lang.Object ref = clientSenderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientSenderId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clientSenderId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientSenderIdBytes() {
      java.lang.Object ref = clientSenderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientSenderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTSENDERIP_FIELD_NUMBER = 3;
    private java.lang.Object clientSenderIp_;
    /**
     * <code>optional string clientSenderIp = 3;</code>
     */
    public boolean hasClientSenderIp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string clientSenderIp = 3;</code>
     */
    public java.lang.String getClientSenderIp() {
      java.lang.Object ref = clientSenderIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientSenderIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clientSenderIp = 3;</code>
     */
    public com.google.protobuf.ByteString
        getClientSenderIpBytes() {
      java.lang.Object ref = clientSenderIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientSenderIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTSENDERPORT_FIELD_NUMBER = 4;
    private int clientSenderPort_;
    /**
     * <code>optional int32 clientSenderPort = 4;</code>
     */
    public boolean hasClientSenderPort() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 clientSenderPort = 4;</code>
     */
    public int getClientSenderPort() {
      return clientSenderPort_;
    }

    public static final int CLIENTRECEIVERID_FIELD_NUMBER = 5;
    private java.lang.Object clientReceiverId_;
    /**
     * <code>optional string clientReceiverId = 5;</code>
     */
    public boolean hasClientReceiverId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string clientReceiverId = 5;</code>
     */
    public java.lang.String getClientReceiverId() {
      java.lang.Object ref = clientReceiverId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientReceiverId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clientReceiverId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getClientReceiverIdBytes() {
      java.lang.Object ref = clientReceiverId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientReceiverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTRECEIVERIP_FIELD_NUMBER = 6;
    private java.lang.Object clientReceiverIp_;
    /**
     * <code>optional string clientReceiverIp = 6;</code>
     */
    public boolean hasClientReceiverIp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string clientReceiverIp = 6;</code>
     */
    public java.lang.String getClientReceiverIp() {
      java.lang.Object ref = clientReceiverIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientReceiverIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clientReceiverIp = 6;</code>
     */
    public com.google.protobuf.ByteString
        getClientReceiverIpBytes() {
      java.lang.Object ref = clientReceiverIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientReceiverIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTRECEIVERPORT_FIELD_NUMBER = 7;
    private int clientReceiverPort_;
    /**
     * <code>optional int32 clientReceiverPort = 7;</code>
     */
    public boolean hasClientReceiverPort() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 clientReceiverPort = 7;</code>
     */
    public int getClientReceiverPort() {
      return clientReceiverPort_;
    }

    public static final int FILENAME_FIELD_NUMBER = 8;
    private java.lang.Object fileName_;
    /**
     * <code>optional string fileName = 8;</code>
     */
    public boolean hasFileName() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string fileName = 8;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string fileName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGEBITS_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString imageBits_;
    /**
     * <code>optional bytes imageBits = 9;</code>
     */
    public boolean hasImageBits() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional bytes imageBits = 9;</code>
     */
    public com.google.protobuf.ByteString getImageBits() {
      return imageBits_;
    }

    private void initFields() {
      message_ = "";
      clientSenderId_ = "";
      clientSenderIp_ = "";
      clientSenderPort_ = 0;
      clientReceiverId_ = "";
      clientReceiverIp_ = "";
      clientReceiverPort_ = 0;
      fileName_ = "";
      imageBits_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getClientSenderIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getClientSenderIpBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, clientSenderPort_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getClientReceiverIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getClientReceiverIpBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, clientReceiverPort_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, imageBits_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getClientSenderIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getClientSenderIpBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, clientSenderPort_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getClientReceiverIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getClientReceiverIpBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, clientReceiverPort_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, imageBits_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static NodeMessageProto.ClientMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NodeMessageProto.ClientMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NodeMessageProto.ClientMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NodeMessageProto.ClientMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NodeMessageProto.ClientMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NodeMessageProto.ClientMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static NodeMessageProto.ClientMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static NodeMessageProto.ClientMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static NodeMessageProto.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NodeMessageProto.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(NodeMessageProto.ClientMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientMessage)
        NodeMessageProto.ClientMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NodeMessageProto.internal_static_ClientMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NodeMessageProto.internal_static_ClientMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NodeMessageProto.ClientMessage.class, NodeMessageProto.ClientMessage.Builder.class);
      }

      // Construct using NodeMessageProto.ClientMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        clientSenderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        clientSenderIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        clientSenderPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        clientReceiverId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        clientReceiverIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        clientReceiverPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        fileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        imageBits_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NodeMessageProto.internal_static_ClientMessage_descriptor;
      }

      public NodeMessageProto.ClientMessage getDefaultInstanceForType() {
        return NodeMessageProto.ClientMessage.getDefaultInstance();
      }

      public NodeMessageProto.ClientMessage build() {
        NodeMessageProto.ClientMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NodeMessageProto.ClientMessage buildPartial() {
        NodeMessageProto.ClientMessage result = new NodeMessageProto.ClientMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientSenderId_ = clientSenderId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.clientSenderIp_ = clientSenderIp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.clientSenderPort_ = clientSenderPort_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.clientReceiverId_ = clientReceiverId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.clientReceiverIp_ = clientReceiverIp_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.clientReceiverPort_ = clientReceiverPort_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.fileName_ = fileName_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.imageBits_ = imageBits_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NodeMessageProto.ClientMessage) {
          return mergeFrom((NodeMessageProto.ClientMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NodeMessageProto.ClientMessage other) {
        if (other == NodeMessageProto.ClientMessage.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          bitField0_ |= 0x00000001;
          message_ = other.message_;
          onChanged();
        }
        if (other.hasClientSenderId()) {
          bitField0_ |= 0x00000002;
          clientSenderId_ = other.clientSenderId_;
          onChanged();
        }
        if (other.hasClientSenderIp()) {
          bitField0_ |= 0x00000004;
          clientSenderIp_ = other.clientSenderIp_;
          onChanged();
        }
        if (other.hasClientSenderPort()) {
          setClientSenderPort(other.getClientSenderPort());
        }
        if (other.hasClientReceiverId()) {
          bitField0_ |= 0x00000010;
          clientReceiverId_ = other.clientReceiverId_;
          onChanged();
        }
        if (other.hasClientReceiverIp()) {
          bitField0_ |= 0x00000020;
          clientReceiverIp_ = other.clientReceiverIp_;
          onChanged();
        }
        if (other.hasClientReceiverPort()) {
          setClientReceiverPort(other.getClientReceiverPort());
        }
        if (other.hasFileName()) {
          bitField0_ |= 0x00000080;
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.hasImageBits()) {
          setImageBits(other.getImageBits());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NodeMessageProto.ClientMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NodeMessageProto.ClientMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 1;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientSenderId_ = "";
      /**
       * <code>optional string clientSenderId = 2;</code>
       */
      public boolean hasClientSenderId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string clientSenderId = 2;</code>
       */
      public java.lang.String getClientSenderId() {
        java.lang.Object ref = clientSenderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientSenderId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientSenderId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClientSenderIdBytes() {
        java.lang.Object ref = clientSenderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientSenderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientSenderId = 2;</code>
       */
      public Builder setClientSenderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientSenderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientSenderId = 2;</code>
       */
      public Builder clearClientSenderId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientSenderId_ = getDefaultInstance().getClientSenderId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientSenderId = 2;</code>
       */
      public Builder setClientSenderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientSenderId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientSenderIp_ = "";
      /**
       * <code>optional string clientSenderIp = 3;</code>
       */
      public boolean hasClientSenderIp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string clientSenderIp = 3;</code>
       */
      public java.lang.String getClientSenderIp() {
        java.lang.Object ref = clientSenderIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientSenderIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientSenderIp = 3;</code>
       */
      public com.google.protobuf.ByteString
          getClientSenderIpBytes() {
        java.lang.Object ref = clientSenderIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientSenderIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientSenderIp = 3;</code>
       */
      public Builder setClientSenderIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        clientSenderIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientSenderIp = 3;</code>
       */
      public Builder clearClientSenderIp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clientSenderIp_ = getDefaultInstance().getClientSenderIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientSenderIp = 3;</code>
       */
      public Builder setClientSenderIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        clientSenderIp_ = value;
        onChanged();
        return this;
      }

      private int clientSenderPort_ ;
      /**
       * <code>optional int32 clientSenderPort = 4;</code>
       */
      public boolean hasClientSenderPort() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 clientSenderPort = 4;</code>
       */
      public int getClientSenderPort() {
        return clientSenderPort_;
      }
      /**
       * <code>optional int32 clientSenderPort = 4;</code>
       */
      public Builder setClientSenderPort(int value) {
        bitField0_ |= 0x00000008;
        clientSenderPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clientSenderPort = 4;</code>
       */
      public Builder clearClientSenderPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        clientSenderPort_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object clientReceiverId_ = "";
      /**
       * <code>optional string clientReceiverId = 5;</code>
       */
      public boolean hasClientReceiverId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string clientReceiverId = 5;</code>
       */
      public java.lang.String getClientReceiverId() {
        java.lang.Object ref = clientReceiverId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientReceiverId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientReceiverId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getClientReceiverIdBytes() {
        java.lang.Object ref = clientReceiverId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientReceiverId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientReceiverId = 5;</code>
       */
      public Builder setClientReceiverId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        clientReceiverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientReceiverId = 5;</code>
       */
      public Builder clearClientReceiverId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        clientReceiverId_ = getDefaultInstance().getClientReceiverId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientReceiverId = 5;</code>
       */
      public Builder setClientReceiverIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        clientReceiverId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientReceiverIp_ = "";
      /**
       * <code>optional string clientReceiverIp = 6;</code>
       */
      public boolean hasClientReceiverIp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string clientReceiverIp = 6;</code>
       */
      public java.lang.String getClientReceiverIp() {
        java.lang.Object ref = clientReceiverIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientReceiverIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientReceiverIp = 6;</code>
       */
      public com.google.protobuf.ByteString
          getClientReceiverIpBytes() {
        java.lang.Object ref = clientReceiverIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientReceiverIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientReceiverIp = 6;</code>
       */
      public Builder setClientReceiverIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        clientReceiverIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientReceiverIp = 6;</code>
       */
      public Builder clearClientReceiverIp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        clientReceiverIp_ = getDefaultInstance().getClientReceiverIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientReceiverIp = 6;</code>
       */
      public Builder setClientReceiverIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        clientReceiverIp_ = value;
        onChanged();
        return this;
      }

      private int clientReceiverPort_ ;
      /**
       * <code>optional int32 clientReceiverPort = 7;</code>
       */
      public boolean hasClientReceiverPort() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 clientReceiverPort = 7;</code>
       */
      public int getClientReceiverPort() {
        return clientReceiverPort_;
      }
      /**
       * <code>optional int32 clientReceiverPort = 7;</code>
       */
      public Builder setClientReceiverPort(int value) {
        bitField0_ |= 0x00000040;
        clientReceiverPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clientReceiverPort = 7;</code>
       */
      public Builder clearClientReceiverPort() {
        bitField0_ = (bitField0_ & ~0x00000040);
        clientReceiverPort_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>optional string fileName = 8;</code>
       */
      public boolean hasFileName() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string fileName = 8;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fileName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string fileName = 8;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string fileName = 8;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string fileName = 8;</code>
       */
      public Builder clearFileName() {
        bitField0_ = (bitField0_ & ~0x00000080);
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string fileName = 8;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        fileName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString imageBits_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes imageBits = 9;</code>
       */
      public boolean hasImageBits() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional bytes imageBits = 9;</code>
       */
      public com.google.protobuf.ByteString getImageBits() {
        return imageBits_;
      }
      /**
       * <code>optional bytes imageBits = 9;</code>
       */
      public Builder setImageBits(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        imageBits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes imageBits = 9;</code>
       */
      public Builder clearImageBits() {
        bitField0_ = (bitField0_ & ~0x00000100);
        imageBits_ = getDefaultInstance().getImageBits();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ClientMessage)
    }

    static {
      defaultInstance = new ClientMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ClientMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClientMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021NodeMessage.proto\"\251\002\n\007Message\022\017\n\007messa" +
      "ge\030\001 \001(\t\022\016\n\006nodeId\030\002 \001(\t\022\016\n\006nodeIp\030\003 \001(\t" +
      "\022\020\n\010nodePort\030\004 \001(\005\022%\n\rclientMessage\030\005 \001(" +
      "\0132\016.ClientMessage\0224\n\013messageType\030\006 \001(\0162\024" +
      ".Message.MessageType:\tHEARTBEAT\"~\n\013Messa" +
      "geType\022\r\n\tHEARTBEAT\020\000\022\016\n\nNOMINATION\020\001\022\010\n" +
      "\004VOTE\020\002\022\033\n\027LOG_REPLICATION_REQUEST\020\003\022)\n%" +
      "LOG_REPLICATION_COMPLETE_NOTIFICATION\020\004\"" +
      "\337\001\n\rClientMessage\022\017\n\007message\030\001 \001(\t\022\026\n\016cl" +
      "ientSenderId\030\002 \001(\t\022\026\n\016clientSenderIp\030\003 \001",
      "(\t\022\030\n\020clientSenderPort\030\004 \001(\005\022\030\n\020clientRe" +
      "ceiverId\030\005 \001(\t\022\030\n\020clientReceiverIp\030\006 \001(\t" +
      "\022\032\n\022clientReceiverPort\030\007 \001(\005\022\020\n\010fileName" +
      "\030\010 \001(\t\022\021\n\timageBits\030\t \001(\014B\022B\020NodeMessage" +
      "Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Message", "NodeId", "NodeIp", "NodePort", "ClientMessage", "MessageType", });
    internal_static_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ClientMessage_descriptor,
        new java.lang.String[] { "Message", "ClientSenderId", "ClientSenderIp", "ClientSenderPort", "ClientReceiverId", "ClientReceiverIp", "ClientReceiverPort", "FileName", "ImageBits", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
