package com.distsc.comm.protobuf;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessage.proto

public final class ClientMessage {
  private ClientMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string msgId = 1;</code>
     */
    boolean hasMsgId();
    /**
     * <code>optional string msgId = 1;</code>
     */
    java.lang.String getMsgId();
    /**
     * <code>optional string msgId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    /**
     * <code>required string senderUserName = 2;</code>
     */
    boolean hasSenderUserName();
    /**
     * <code>required string senderUserName = 2;</code>
     */
    java.lang.String getSenderUserName();
    /**
     * <code>required string senderUserName = 2;</code>
     */
    com.google.protobuf.ByteString
        getSenderUserNameBytes();

    /**
     * <code>required string receiverUserName = 3;</code>
     */
    boolean hasReceiverUserName();
    /**
     * <code>required string receiverUserName = 3;</code>
     */
    java.lang.String getReceiverUserName();
    /**
     * <code>required string receiverUserName = 3;</code>
     */
    com.google.protobuf.ByteString
        getReceiverUserNameBytes();

    /**
     * <code>optional string msgText = 4;</code>
     */
    boolean hasMsgText();
    /**
     * <code>optional string msgText = 4;</code>
     */
    java.lang.String getMsgText();
    /**
     * <code>optional string msgText = 4;</code>
     */
    com.google.protobuf.ByteString
        getMsgTextBytes();

    /**
     * <code>optional string msgImageName = 5;</code>
     */
    boolean hasMsgImageName();
    /**
     * <code>optional string msgImageName = 5;</code>
     */
    java.lang.String getMsgImageName();
    /**
     * <code>optional string msgImageName = 5;</code>
     */
    com.google.protobuf.ByteString
        getMsgImageNameBytes();

    /**
     * <code>optional bytes msgImageBits = 6;</code>
     */
    boolean hasMsgImageBits();
    /**
     * <code>optional bytes msgImageBits = 6;</code>
     */
    com.google.protobuf.ByteString getMsgImageBits();

    /**
     * <code>optional string checksumMsgText = 7;</code>
     */
    boolean hasChecksumMsgText();
    /**
     * <code>optional string checksumMsgText = 7;</code>
     */
    java.lang.String getChecksumMsgText();
    /**
     * <code>optional string checksumMsgText = 7;</code>
     */
    com.google.protobuf.ByteString
        getChecksumMsgTextBytes();

    /**
     * <code>optional string checksumImageBits = 8;</code>
     */
    boolean hasChecksumImageBits();
    /**
     * <code>optional string checksumImageBits = 8;</code>
     */
    java.lang.String getChecksumImageBits();
    /**
     * <code>optional string checksumImageBits = 8;</code>
     */
    com.google.protobuf.ByteString
        getChecksumImageBitsBytes();

    /**
     * <code>optional .ClientMsg.MessageType messageType = 9 [default = LOGIN];</code>
     */
    boolean hasMessageType();
    /**
     * <code>optional .ClientMsg.MessageType messageType = 9 [default = LOGIN];</code>
     */
    ClientMessage.ClientMsg.MessageType getMessageType();

    /**
     * <code>optional .ClientMsg.ErrorType errorType = 10 [default = INVALID_LEADER];</code>
     */
    boolean hasErrorType();
    /**
     * <code>optional .ClientMsg.ErrorType errorType = 10 [default = INVALID_LEADER];</code>
     */
    ClientMessage.ClientMsg.ErrorType getErrorType();
  }
  /**
   * Protobuf type {@code ClientMsg}
   */
  public static final class ClientMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ClientMsg)
      ClientMsgOrBuilder {
    // Use ClientMsg.newBuilder() to construct.
    private ClientMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientMsg defaultInstance;
    public static ClientMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ClientMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              msgId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              senderUserName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              receiverUserName_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              msgText_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              msgImageName_ = bs;
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              msgImageBits_ = input.readBytes();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              checksumMsgText_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              checksumImageBits_ = bs;
              break;
            }
            case 72: {
              int rawValue = input.readEnum();
              ClientMessage.ClientMsg.MessageType value = ClientMessage.ClientMsg.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(9, rawValue);
              } else {
                bitField0_ |= 0x00000100;
                messageType_ = value;
              }
              break;
            }
            case 80: {
              int rawValue = input.readEnum();
              ClientMessage.ClientMsg.ErrorType value = ClientMessage.ClientMsg.ErrorType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(10, rawValue);
              } else {
                bitField0_ |= 0x00000200;
                errorType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientMessage.internal_static_ClientMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientMessage.internal_static_ClientMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientMessage.ClientMsg.class, ClientMessage.ClientMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientMsg> PARSER =
        new com.google.protobuf.AbstractParser<ClientMsg>() {
      public ClientMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientMsg> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code ClientMsg.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LOGIN = 0;</code>
       */
      LOGIN(0, 0),
      /**
       * <code>MESSAGE = 1;</code>
       */
      MESSAGE(1, 1),
      /**
       * <code>ACKNOWLEDGE = 2;</code>
       */
      ACKNOWLEDGE(2, 2),
      /**
       * <code>ERROR = 3;</code>
       */
      ERROR(3, 3),
      /**
       * <code>LOGOUT = 4;</code>
       */
      LOGOUT(4, 4),
      ;

      /**
       * <code>LOGIN = 0;</code>
       */
      public static final int LOGIN_VALUE = 0;
      /**
       * <code>MESSAGE = 1;</code>
       */
      public static final int MESSAGE_VALUE = 1;
      /**
       * <code>ACKNOWLEDGE = 2;</code>
       */
      public static final int ACKNOWLEDGE_VALUE = 2;
      /**
       * <code>ERROR = 3;</code>
       */
      public static final int ERROR_VALUE = 3;
      /**
       * <code>LOGOUT = 4;</code>
       */
      public static final int LOGOUT_VALUE = 4;


      public final int getNumber() { return value; }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 0: return LOGIN;
          case 1: return MESSAGE;
          case 2: return ACKNOWLEDGE;
          case 3: return ERROR;
          case 4: return LOGOUT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ClientMessage.ClientMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ClientMsg.MessageType)
    }

    /**
     * Protobuf enum {@code ClientMsg.ErrorType}
     */
    public enum ErrorType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>INVALID_LEADER = 0;</code>
       */
      INVALID_LEADER(0, 0),
      /**
       * <code>MESSAGE_CORRUPT = 1;</code>
       */
      MESSAGE_CORRUPT(1, 1),
      /**
       * <code>DELIVERY_FAIL = 2;</code>
       */
      DELIVERY_FAIL(2, 2),
      /**
       * <code>MESSAGE_SIZE = 3;</code>
       */
      MESSAGE_SIZE(3, 3),
      /**
       * <code>INVALID_LOGIN = 4;</code>
       */
      INVALID_LOGIN(4, 4),
      ;

      /**
       * <code>INVALID_LEADER = 0;</code>
       */
      public static final int INVALID_LEADER_VALUE = 0;
      /**
       * <code>MESSAGE_CORRUPT = 1;</code>
       */
      public static final int MESSAGE_CORRUPT_VALUE = 1;
      /**
       * <code>DELIVERY_FAIL = 2;</code>
       */
      public static final int DELIVERY_FAIL_VALUE = 2;
      /**
       * <code>MESSAGE_SIZE = 3;</code>
       */
      public static final int MESSAGE_SIZE_VALUE = 3;
      /**
       * <code>INVALID_LOGIN = 4;</code>
       */
      public static final int INVALID_LOGIN_VALUE = 4;


      public final int getNumber() { return value; }

      public static ErrorType valueOf(int value) {
        switch (value) {
          case 0: return INVALID_LEADER;
          case 1: return MESSAGE_CORRUPT;
          case 2: return DELIVERY_FAIL;
          case 3: return MESSAGE_SIZE;
          case 4: return INVALID_LOGIN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ErrorType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ErrorType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ErrorType>() {
              public ErrorType findValueByNumber(int number) {
                return ErrorType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ClientMessage.ClientMsg.getDescriptor().getEnumTypes().get(1);
      }

      private static final ErrorType[] VALUES = values();

      public static ErrorType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ErrorType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ClientMsg.ErrorType)
    }

    private int bitField0_;
    public static final int MSGID_FIELD_NUMBER = 1;
    private java.lang.Object msgId_;
    /**
     * <code>optional string msgId = 1;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string msgId = 1;</code>
     */
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERUSERNAME_FIELD_NUMBER = 2;
    private java.lang.Object senderUserName_;
    /**
     * <code>required string senderUserName = 2;</code>
     */
    public boolean hasSenderUserName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string senderUserName = 2;</code>
     */
    public java.lang.String getSenderUserName() {
      java.lang.Object ref = senderUserName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderUserName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string senderUserName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSenderUserNameBytes() {
      java.lang.Object ref = senderUserName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderUserName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERUSERNAME_FIELD_NUMBER = 3;
    private java.lang.Object receiverUserName_;
    /**
     * <code>required string receiverUserName = 3;</code>
     */
    public boolean hasReceiverUserName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string receiverUserName = 3;</code>
     */
    public java.lang.String getReceiverUserName() {
      java.lang.Object ref = receiverUserName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          receiverUserName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string receiverUserName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverUserNameBytes() {
      java.lang.Object ref = receiverUserName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverUserName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGTEXT_FIELD_NUMBER = 4;
    private java.lang.Object msgText_;
    /**
     * <code>optional string msgText = 4;</code>
     */
    public boolean hasMsgText() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string msgText = 4;</code>
     */
    public java.lang.String getMsgText() {
      java.lang.Object ref = msgText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgText = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMsgTextBytes() {
      java.lang.Object ref = msgText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGIMAGENAME_FIELD_NUMBER = 5;
    private java.lang.Object msgImageName_;
    /**
     * <code>optional string msgImageName = 5;</code>
     */
    public boolean hasMsgImageName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string msgImageName = 5;</code>
     */
    public java.lang.String getMsgImageName() {
      java.lang.Object ref = msgImageName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgImageName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgImageName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMsgImageNameBytes() {
      java.lang.Object ref = msgImageName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgImageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGIMAGEBITS_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString msgImageBits_;
    /**
     * <code>optional bytes msgImageBits = 6;</code>
     */
    public boolean hasMsgImageBits() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes msgImageBits = 6;</code>
     */
    public com.google.protobuf.ByteString getMsgImageBits() {
      return msgImageBits_;
    }

    public static final int CHECKSUMMSGTEXT_FIELD_NUMBER = 7;
    private java.lang.Object checksumMsgText_;
    /**
     * <code>optional string checksumMsgText = 7;</code>
     */
    public boolean hasChecksumMsgText() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string checksumMsgText = 7;</code>
     */
    public java.lang.String getChecksumMsgText() {
      java.lang.Object ref = checksumMsgText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          checksumMsgText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string checksumMsgText = 7;</code>
     */
    public com.google.protobuf.ByteString
        getChecksumMsgTextBytes() {
      java.lang.Object ref = checksumMsgText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        checksumMsgText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHECKSUMIMAGEBITS_FIELD_NUMBER = 8;
    private java.lang.Object checksumImageBits_;
    /**
     * <code>optional string checksumImageBits = 8;</code>
     */
    public boolean hasChecksumImageBits() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string checksumImageBits = 8;</code>
     */
    public java.lang.String getChecksumImageBits() {
      java.lang.Object ref = checksumImageBits_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          checksumImageBits_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string checksumImageBits = 8;</code>
     */
    public com.google.protobuf.ByteString
        getChecksumImageBitsBytes() {
      java.lang.Object ref = checksumImageBits_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        checksumImageBits_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 9;
    private ClientMessage.ClientMsg.MessageType messageType_;
    /**
     * <code>optional .ClientMsg.MessageType messageType = 9 [default = LOGIN];</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional .ClientMsg.MessageType messageType = 9 [default = LOGIN];</code>
     */
    public ClientMessage.ClientMsg.MessageType getMessageType() {
      return messageType_;
    }

    public static final int ERRORTYPE_FIELD_NUMBER = 10;
    private ClientMessage.ClientMsg.ErrorType errorType_;
    /**
     * <code>optional .ClientMsg.ErrorType errorType = 10 [default = INVALID_LEADER];</code>
     */
    public boolean hasErrorType() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional .ClientMsg.ErrorType errorType = 10 [default = INVALID_LEADER];</code>
     */
    public ClientMessage.ClientMsg.ErrorType getErrorType() {
      return errorType_;
    }

    private void initFields() {
      msgId_ = "";
      senderUserName_ = "";
      receiverUserName_ = "";
      msgText_ = "";
      msgImageName_ = "";
      msgImageBits_ = com.google.protobuf.ByteString.EMPTY;
      checksumMsgText_ = "";
      checksumImageBits_ = "";
      messageType_ = ClientMessage.ClientMsg.MessageType.LOGIN;
      errorType_ = ClientMessage.ClientMsg.ErrorType.INVALID_LEADER;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSenderUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReceiverUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSenderUserNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getReceiverUserNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getMsgTextBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getMsgImageNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, msgImageBits_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getChecksumMsgTextBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getChecksumImageBitsBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeEnum(9, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeEnum(10, errorType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSenderUserNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getReceiverUserNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMsgTextBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMsgImageNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, msgImageBits_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getChecksumMsgTextBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getChecksumImageBitsBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(10, errorType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ClientMessage.ClientMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientMessage.ClientMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientMessage.ClientMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientMessage.ClientMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientMessage.ClientMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientMessage.ClientMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ClientMessage.ClientMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ClientMessage.ClientMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ClientMessage.ClientMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientMessage.ClientMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ClientMessage.ClientMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientMsg)
        ClientMessage.ClientMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientMessage.internal_static_ClientMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientMessage.internal_static_ClientMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientMessage.ClientMsg.class, ClientMessage.ClientMsg.Builder.class);
      }

      // Construct using ClientMessage.ClientMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        senderUserName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        receiverUserName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        msgText_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        msgImageName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        msgImageBits_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        checksumMsgText_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        checksumImageBits_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        messageType_ = ClientMessage.ClientMsg.MessageType.LOGIN;
        bitField0_ = (bitField0_ & ~0x00000100);
        errorType_ = ClientMessage.ClientMsg.ErrorType.INVALID_LEADER;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClientMessage.internal_static_ClientMsg_descriptor;
      }

      public ClientMessage.ClientMsg getDefaultInstanceForType() {
        return ClientMessage.ClientMsg.getDefaultInstance();
      }

      public ClientMessage.ClientMsg build() {
        ClientMessage.ClientMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ClientMessage.ClientMsg buildPartial() {
        ClientMessage.ClientMsg result = new ClientMessage.ClientMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.senderUserName_ = senderUserName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.receiverUserName_ = receiverUserName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.msgText_ = msgText_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msgImageName_ = msgImageName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.msgImageBits_ = msgImageBits_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.checksumMsgText_ = checksumMsgText_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.checksumImageBits_ = checksumImageBits_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.errorType_ = errorType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientMessage.ClientMsg) {
          return mergeFrom((ClientMessage.ClientMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientMessage.ClientMsg other) {
        if (other == ClientMessage.ClientMsg.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          bitField0_ |= 0x00000001;
          msgId_ = other.msgId_;
          onChanged();
        }
        if (other.hasSenderUserName()) {
          bitField0_ |= 0x00000002;
          senderUserName_ = other.senderUserName_;
          onChanged();
        }
        if (other.hasReceiverUserName()) {
          bitField0_ |= 0x00000004;
          receiverUserName_ = other.receiverUserName_;
          onChanged();
        }
        if (other.hasMsgText()) {
          bitField0_ |= 0x00000008;
          msgText_ = other.msgText_;
          onChanged();
        }
        if (other.hasMsgImageName()) {
          bitField0_ |= 0x00000010;
          msgImageName_ = other.msgImageName_;
          onChanged();
        }
        if (other.hasMsgImageBits()) {
          setMsgImageBits(other.getMsgImageBits());
        }
        if (other.hasChecksumMsgText()) {
          bitField0_ |= 0x00000040;
          checksumMsgText_ = other.checksumMsgText_;
          onChanged();
        }
        if (other.hasChecksumImageBits()) {
          bitField0_ |= 0x00000080;
          checksumImageBits_ = other.checksumImageBits_;
          onChanged();
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasErrorType()) {
          setErrorType(other.getErrorType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSenderUserName()) {
          
          return false;
        }
        if (!hasReceiverUserName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClientMessage.ClientMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ClientMessage.ClientMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object msgId_ = "";
      /**
       * <code>optional string msgId = 1;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string msgId = 1;</code>
       */
      public java.lang.String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        java.lang.Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgId = 1;</code>
       */
      public Builder setMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msgId = 1;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msgId = 1;</code>
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderUserName_ = "";
      /**
       * <code>required string senderUserName = 2;</code>
       */
      public boolean hasSenderUserName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string senderUserName = 2;</code>
       */
      public java.lang.String getSenderUserName() {
        java.lang.Object ref = senderUserName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            senderUserName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string senderUserName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSenderUserNameBytes() {
        java.lang.Object ref = senderUserName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderUserName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string senderUserName = 2;</code>
       */
      public Builder setSenderUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        senderUserName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string senderUserName = 2;</code>
       */
      public Builder clearSenderUserName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        senderUserName_ = getDefaultInstance().getSenderUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string senderUserName = 2;</code>
       */
      public Builder setSenderUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        senderUserName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverUserName_ = "";
      /**
       * <code>required string receiverUserName = 3;</code>
       */
      public boolean hasReceiverUserName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string receiverUserName = 3;</code>
       */
      public java.lang.String getReceiverUserName() {
        java.lang.Object ref = receiverUserName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            receiverUserName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string receiverUserName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverUserNameBytes() {
        java.lang.Object ref = receiverUserName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverUserName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string receiverUserName = 3;</code>
       */
      public Builder setReceiverUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        receiverUserName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string receiverUserName = 3;</code>
       */
      public Builder clearReceiverUserName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        receiverUserName_ = getDefaultInstance().getReceiverUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string receiverUserName = 3;</code>
       */
      public Builder setReceiverUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        receiverUserName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msgText_ = "";
      /**
       * <code>optional string msgText = 4;</code>
       */
      public boolean hasMsgText() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string msgText = 4;</code>
       */
      public java.lang.String getMsgText() {
        java.lang.Object ref = msgText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgText = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMsgTextBytes() {
        java.lang.Object ref = msgText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgText = 4;</code>
       */
      public Builder setMsgText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        msgText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msgText = 4;</code>
       */
      public Builder clearMsgText() {
        bitField0_ = (bitField0_ & ~0x00000008);
        msgText_ = getDefaultInstance().getMsgText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msgText = 4;</code>
       */
      public Builder setMsgTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        msgText_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msgImageName_ = "";
      /**
       * <code>optional string msgImageName = 5;</code>
       */
      public boolean hasMsgImageName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string msgImageName = 5;</code>
       */
      public java.lang.String getMsgImageName() {
        java.lang.Object ref = msgImageName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgImageName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgImageName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMsgImageNameBytes() {
        java.lang.Object ref = msgImageName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgImageName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgImageName = 5;</code>
       */
      public Builder setMsgImageName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msgImageName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msgImageName = 5;</code>
       */
      public Builder clearMsgImageName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgImageName_ = getDefaultInstance().getMsgImageName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msgImageName = 5;</code>
       */
      public Builder setMsgImageNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msgImageName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msgImageBits_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes msgImageBits = 6;</code>
       */
      public boolean hasMsgImageBits() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes msgImageBits = 6;</code>
       */
      public com.google.protobuf.ByteString getMsgImageBits() {
        return msgImageBits_;
      }
      /**
       * <code>optional bytes msgImageBits = 6;</code>
       */
      public Builder setMsgImageBits(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        msgImageBits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes msgImageBits = 6;</code>
       */
      public Builder clearMsgImageBits() {
        bitField0_ = (bitField0_ & ~0x00000020);
        msgImageBits_ = getDefaultInstance().getMsgImageBits();
        onChanged();
        return this;
      }

      private java.lang.Object checksumMsgText_ = "";
      /**
       * <code>optional string checksumMsgText = 7;</code>
       */
      public boolean hasChecksumMsgText() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string checksumMsgText = 7;</code>
       */
      public java.lang.String getChecksumMsgText() {
        java.lang.Object ref = checksumMsgText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            checksumMsgText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string checksumMsgText = 7;</code>
       */
      public com.google.protobuf.ByteString
          getChecksumMsgTextBytes() {
        java.lang.Object ref = checksumMsgText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          checksumMsgText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string checksumMsgText = 7;</code>
       */
      public Builder setChecksumMsgText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        checksumMsgText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string checksumMsgText = 7;</code>
       */
      public Builder clearChecksumMsgText() {
        bitField0_ = (bitField0_ & ~0x00000040);
        checksumMsgText_ = getDefaultInstance().getChecksumMsgText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string checksumMsgText = 7;</code>
       */
      public Builder setChecksumMsgTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        checksumMsgText_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object checksumImageBits_ = "";
      /**
       * <code>optional string checksumImageBits = 8;</code>
       */
      public boolean hasChecksumImageBits() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string checksumImageBits = 8;</code>
       */
      public java.lang.String getChecksumImageBits() {
        java.lang.Object ref = checksumImageBits_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            checksumImageBits_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string checksumImageBits = 8;</code>
       */
      public com.google.protobuf.ByteString
          getChecksumImageBitsBytes() {
        java.lang.Object ref = checksumImageBits_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          checksumImageBits_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string checksumImageBits = 8;</code>
       */
      public Builder setChecksumImageBits(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        checksumImageBits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string checksumImageBits = 8;</code>
       */
      public Builder clearChecksumImageBits() {
        bitField0_ = (bitField0_ & ~0x00000080);
        checksumImageBits_ = getDefaultInstance().getChecksumImageBits();
        onChanged();
        return this;
      }
      /**
       * <code>optional string checksumImageBits = 8;</code>
       */
      public Builder setChecksumImageBitsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        checksumImageBits_ = value;
        onChanged();
        return this;
      }

      private ClientMessage.ClientMsg.MessageType messageType_ = ClientMessage.ClientMsg.MessageType.LOGIN;
      /**
       * <code>optional .ClientMsg.MessageType messageType = 9 [default = LOGIN];</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional .ClientMsg.MessageType messageType = 9 [default = LOGIN];</code>
       */
      public ClientMessage.ClientMsg.MessageType getMessageType() {
        return messageType_;
      }
      /**
       * <code>optional .ClientMsg.MessageType messageType = 9 [default = LOGIN];</code>
       */
      public Builder setMessageType(ClientMessage.ClientMsg.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000100;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .ClientMsg.MessageType messageType = 9 [default = LOGIN];</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000100);
        messageType_ = ClientMessage.ClientMsg.MessageType.LOGIN;
        onChanged();
        return this;
      }

      private ClientMessage.ClientMsg.ErrorType errorType_ = ClientMessage.ClientMsg.ErrorType.INVALID_LEADER;
      /**
       * <code>optional .ClientMsg.ErrorType errorType = 10 [default = INVALID_LEADER];</code>
       */
      public boolean hasErrorType() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional .ClientMsg.ErrorType errorType = 10 [default = INVALID_LEADER];</code>
       */
      public ClientMessage.ClientMsg.ErrorType getErrorType() {
        return errorType_;
      }
      /**
       * <code>optional .ClientMsg.ErrorType errorType = 10 [default = INVALID_LEADER];</code>
       */
      public Builder setErrorType(ClientMessage.ClientMsg.ErrorType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000200;
        errorType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .ClientMsg.ErrorType errorType = 10 [default = INVALID_LEADER];</code>
       */
      public Builder clearErrorType() {
        bitField0_ = (bitField0_ & ~0x00000200);
        errorType_ = ClientMessage.ClientMsg.ErrorType.INVALID_LEADER;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ClientMsg)
    }

    static {
      defaultInstance = new ClientMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ClientMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClientMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClientMessage.proto\"\347\003\n\tClientMsg\022\r\n\005m" +
      "sgId\030\001 \001(\t\022\026\n\016senderUserName\030\002 \002(\t\022\030\n\020re" +
      "ceiverUserName\030\003 \002(\t\022\017\n\007msgText\030\004 \001(\t\022\024\n" +
      "\014msgImageName\030\005 \001(\t\022\024\n\014msgImageBits\030\006 \001(" +
      "\014\022\027\n\017checksumMsgText\030\007 \001(\t\022\031\n\021checksumIm" +
      "ageBits\030\010 \001(\t\0222\n\013messageType\030\t \001(\0162\026.Cli" +
      "entMsg.MessageType:\005LOGIN\0227\n\terrorType\030\n" +
      " \001(\0162\024.ClientMsg.ErrorType:\016INVALID_LEAD" +
      "ER\"M\n\013MessageType\022\t\n\005LOGIN\020\000\022\013\n\007MESSAGE\020" +
      "\001\022\017\n\013ACKNOWLEDGE\020\002\022\t\n\005ERROR\020\003\022\n\n\006LOGOUT\020",
      "\004\"l\n\tErrorType\022\022\n\016INVALID_LEADER\020\000\022\023\n\017ME" +
      "SSAGE_CORRUPT\020\001\022\021\n\rDELIVERY_FAIL\020\002\022\020\n\014ME" +
      "SSAGE_SIZE\020\003\022\021\n\rINVALID_LOGIN\020\004B\017B\rClien" +
      "tMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ClientMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ClientMsg_descriptor,
        new java.lang.String[] { "MsgId", "SenderUserName", "ReceiverUserName", "MsgText", "MsgImageName", "MsgImageBits", "ChecksumMsgText", "ChecksumImageBits", "MessageType", "ErrorType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
